# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
target_protein_MR:
  - ADM
  - AGRP
  - Beta-NGF
  - CA-125
  - CASP-8
  - CCL20
  - CCL3
  - CCL4
  - CD40
  - CHI3L1
  - CSF-1
  - CSTB
  - CTSD
  - CTSL1
  - CX3CL1
  - CXCL1
  - CXCL16
  - CXCL6
  - Dkk-1
  - ECP
  - EGF
  - EN-RAGE
  - ESM-1
  - FABP4
  - FAS
  - FGF-23
  - FS
  - GAL
  - GDF-15
  - GH
  - Gal-3
  - HB-EGF
  - HGF
  - HSP
  - IL-18
  - IL-1ra
  - IL-27
  - IL-6
  - IL-6RA
  - IL-8
  - IL16
  - KIM-1
  - KLK6
  - LEP
  - LOX-1
  - MB
  - MCP-1
  - MMP-1
  - MMP-10
  - MMP-12
  - MMP-3
  - MMP-7
  - MPO
  - NT-pro_BNP
  - OPG
  - PAPPA
  - PAR-1
  - PDGF
  - PECAM-1
  - PSGL-1
  - PTX3
  - PlGF
  - RAGE
  - REN
  - RETN
  - SCF
  - SELE
  - SIRT2
  - SPON1
  - ST2
  - TF
  - TIE2
  - TM
  - TNF-R1
  - TNF-R2
  - TNFSF14
  - TRAIL
  - TRAIL-R2
  - TRANCE
  - U-PAR
  - VEGF-A
  - hK11
  - t-PA
